name: Build C++ (sample)

on:
  push:
    paths:
      - '**.cpp'
      - '.github/workflows/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build sample file (Two Sum) just to verify toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y g++
          g++ -std=c++17 Arrays/two_sum.cpp -o two_sum
          ./two_sum
